# Generated by Django 4.1.2 on 2022-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], max_length=10, null=True),
        ),
    ]
