# Generated by Django 4.1.2 on 2022-10-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountactivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountactivation',
            old_name='user_mail',
            new_name='email',
        ),
    ]
