# Generated by Django 4.1.2 on 2022-11-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_schooladmin_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
