# Generated by Django 4.1.2 on 2022-11-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='company_name',
            new_name='name',
        ),
    ]
