# Generated by Django 4.1.2 on 2022-11-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_channel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
