# Generated by Django 4.1.2 on 2022-11-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_channelactivationcode_alter_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='company_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
